import { DEFAULT_CATEGORIES } from './constants.js';

export const mockCategories = DEFAULT_CATEGORIES;

export const mockExpenses = [
  {
    id: '1',
    amount: 120.50,
    date: '2026-01-01',
    note: 'Lunch',
    category_id: '1',
    is_essential: true,
    categories: mockCategories[0],
  },
  {
    id: '2',
    amount: 35.00,
    date: '2026-01-01',
    note: 'Subway',
    category_id: '2',
    is_essential: true,
    categories: mockCategories[1],
  },
  {
    id: '3',
    amount: 299.00,
    date: '2026-01-02',
    note: 'New Clothes',
    category_id: '3',
    is_essential: false,
    categories: mockCategories[2],
  },
  {
    id: '4',
    amount: 85.00,
    date: '2026-01-02',
    note: 'Dinner',
    category_id: '1',
    is_essential: true,
    categories: mockCategories[0],
  },
  {
    id: '5',
    amount: 45.00,
    date: '2026-01-03',
    note: 'Taxi',
    category_id: '2',
    is_essential: false,
    categories: mockCategories[1],
  },
  {
    id: '6',
    amount: 150.00,
    date: '2026-01-03',
    note: 'Game Top-up',
    category_id: '4',
    is_essential: false,
    categories: mockCategories[3],
  },
  {
    id: '7',
    amount: 68.00,
    date: '2026-01-04',
    note: 'Breakfast and Lunch',
    category_id: '1',
    is_essential: true,
    categories: mockCategories[0],
  },
  {
    id: '8',
    amount: 25.00,
    date: '2026-01-04',
    note: 'Bus',
    category_id: '2',
    is_essential: true,
    categories: mockCategories[1],
  },
  {
    id: '9',
    amount: 599.00,
    date: '2026-01-05',
    note: 'Rent',
    category_id: '7',
    is_essential: true,
    categories: mockCategories[6],
  },
  {
    id: '10',
    amount: 120.00,
    date: '2026-01-05',
    note: 'Pharmacy',
    category_id: '5',
    is_essential: true,
    categories: mockCategories[4],
  },
  {
    id: '11',
    amount: 89.00,
    date: '2026-01-06',
    note: 'Weekend Meal',
    category_id: '1',
    is_essential: false,
    categories: mockCategories[0],
  },
  {
    id: '12',
    amount: 199.00,
    date: '2026-01-06',
    note: 'Movie Ticket',
    category_id: '4',
    is_essential: false,
    categories: mockCategories[3],
  },
  {
    id: '13',
    amount: 45.00,
    date: '2026-01-07',
    note: 'Coffee',
    category_id: '1',
    is_essential: false,
    categories: mockCategories[0],
  },
  {
    id: '14',
    amount: 150.00,
    date: '2026-01-08',
    note: 'Lunch',
    category_id: '1',
    is_essential: true,
    categories: mockCategories[0],
  },
  {
    id: '15',
    amount: 35.00,
    date: '2026-01-08',
    note: 'Subway',
    category_id: '2',
    is_essential: true,
    categories: mockCategories[1],
  },
  {
    id: '16',
    amount: 499.00,
    date: '2026-01-09',
    note: 'Books',
    category_id: '6',
    is_essential: false,
    categories: mockCategories[5],
  },
  {
    id: '17',
    amount: 75.00,
    date: '2026-01-09',
    note: 'Dinner',
    category_id: '1',
    is_essential: true,
    categories: mockCategories[0],
  },
  {
    id: '18',
    amount: 120.00,
    date: '2026-01-10',
    note: 'Supermarket Shopping',
    category_id: '3',
    is_essential: true,
    categories: mockCategories[2],
  },
  {
    id: '19',
    amount: 45.00,
    date: '2026-01-10',
    note: 'Taxi',
    category_id: '2',
    is_essential: false,
    categories: mockCategories[1],
  },
  {
    id: '20',
    amount: 88.00,
    date: '2026-01-11',
    note: 'Lunch',
    category_id: '1',
    is_essential: true,
    categories: mockCategories[0],
  },
];

export const mockBudgetAdjustments = [
  {
    id: '1',
    date: '2026-01-01',
    budget_amount: 200.00,
    reason: 'New Year Holiday',
  },
];
